services:

  nginx:
    restart: always
    image: nginx:1.27-alpine
    container_name: nginx
    volumes:
      - ./config/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./config/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
      - TZ=Europe/Moscow
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local_net

  pgsql:
    restart: always
    image: postgres:17.2-alpine
    container_name: pgsql
    volumes:
      - pgsql-vol:/var/lib/postgresql/data
      - ./backup:/home/backup
    environment:
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_PASSWORD=${PGSQL_PASS}
      - POSTGRES_DB=${PGSQL_NAME}
      - TZ=Europe/Moscow
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local_net

  pgadmin:
    restart: always
    image: dpage/pgadmin4:8.14.0
    container_name: pgadmin
    volumes:
      - pgadmin-vol:/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
      - TZ=Europe/Moscow
    ports:
      - "5050:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local_net
    depends_on:
      - pgsql

  mysql:
    restart: always
    image: mysql:8-debian
    container_name: mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --sql-mode=''
    volumes:
      - mysql-vol:/var/lib/mysql
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_DATABASE=${MYSQL_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - TZ=Europe/Moscow
    ports:
      - "3306:3306"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local_net

  phpmyadmin:
    restart: always
    image: phpmyadmin:5.2.1-apache
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_PMADB=phpmyadmin
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
      - TZ=Europe/Moscow
    ports:
      - "5070:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local_net
    depends_on:
      - mysql

  redis:
    restart: always
    image: redis:7.2-alpine
    container_name: redis
    volumes:
      - redis-vol:/data
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/Moscow
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local_net

volumes:
  mysql-vol:
  pgsql-vol:
  pgadmin-vol:
  redis-vol:

networks:
  local_net:
    driver: bridge