version: '3.3'

services:

  nginx:
    restart: always
    image: nginx:1.22.0
    container_name: nginx
    environment:
      - NGINX_ENTRYPOINT_QUIET_LOGS=1
    volumes:
      - ./config/etc/nginx/conf.d:/etc/nginx/conf.d
      - ./config/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local_net

  pgsql:
    restart: always
    image: postgres:12.12
    container_name: pgsql
    volumes:
      - pgsql-vol:/var/lib/postgresql/data
      - ./backup:/home/backup
    environment:
      - POSTGRES_USER=${PGSQL_USER}
      - POSTGRES_PASSWORD=${PGSQL_PASS}
      - POSTGRES_DB=${PGSQL_NAME}
    ports:
      - "5432:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local_net

  pgadmin:
    restart: always
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - pgadmin-vol:/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
    ports:
      - "5050:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local_net
    depends_on:
      - pgsql
    links:
      - pgsql

  mysql:
    restart: always
    image: mysql:8-debian
    container_name: mysql
    volumes:
      - mysql-vol:/var/lib/mysql
    ports:
      - "3306:3306"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local_net
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_DATABASE=${MYSQL_NAME}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}

  phpmyadmin:
    restart: always
    image: phpmyadmin:5.2-apache
    container_name: phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
      - PMA_PMADB=phpmyadmin
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
    ports:
      - "5070:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local_net
    depends_on:
      - mysql
    links:
      - mysql

  redis:
    restart: always
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - local_net

volumes:
  mysql-vol:
  pgsql-vol:
  pgadmin-vol:

networks:
  local_net:
    driver: bridge